export const EmployerSkills = [
  { label: 'I don’t know , Need advice', value: 'I don’t know , Need advice' },
  { label: 'Laravel', value: 'Laravel' },
  { label: 'Django', value: 'Django' },
  { label: 'Flutter', value: 'Flutter' },
  { label: 'Java', value: 'Java' },
  { label: 'Kubernetes', value: 'Kubernetes' },
  { label: 'ELK Stack', value: 'ELK Stack' },
  { label: 'Selenium', value: 'Selenium' },
  { label: 'Backbone.js', value: 'Backbone.js' },
  { label: 'Python', value: 'Python' },
  { label: 'WordPress', value: 'WordPress' },
  { label: 'Golang', value: 'Golang' },
  { label: 'MEAN', value: 'MEAN' },
  { label: 'MERN', value: 'MERN' },
  { label: 'LAMP', value: 'LAMP' },
  { label: 'Kotlin', value: 'Kotlin' },
  { label: 'SQL', value: 'SQL' },
  { label: 'TypeScript', value: 'TypeScript' },
  { label: 'Android', value: 'Android' },
  { label: 'Dart', value: 'Dart' },
  { label: 'React', value: 'React' },
  { label: 'Clojure', value: 'Clojure' },
  { label: 'XML', value: 'XML' },
  { label: 'iOS', value: 'iOS' },
  { label: 'Node.js', value: 'Node.js' },
  { label: 'PostgreSQL', value: 'PostgreSQL' },
  { label: 'C#', value: 'C#' },
  { label: '.NET', value: '.NET' },
  { label: 'PHP', value: 'PHP' },
  { label: 'MongoDB', value: 'MongoDB' },
  { label: 'Angular', value: 'Angular' },
  { label: 'Swift', value: 'Swift' },
  { label: 'Ruby on Rails', value: 'Ruby on Rails' },
  { label: 'Vue.js', value: 'Vue.js' },
  { label: 'Redux', value: 'Redux' },
  { label: 'Elixir', value: 'Elixir' },
  { label: 'Rust', value: 'Rust' },
  { label: 'Haskell', value: 'Haskell' },
  { label: 'Bash', value: 'Bash' },
  { label: 'AWS', value: 'AWS' },
  { label: 'C++', value: 'C++' },
  { label: 'GCP', value: 'GCP' },
  { label: 'Electron', value: 'Electron' },
  { label: 'HTML5', value: 'HTML5' },
  { label: 'Cassandra', value: 'Cassandra' },
  { label: 'NextJS', value: 'NextJS' },
  { label: 'CSS', value: 'CSS' },
  { label: 'Spring', value: 'Spring' },
  { label: 'D3.js', value: 'D3.js' },
  { label: 'HTML', value: 'HTML' },
  { label: 'React Native', value: 'React Native' },
  { label: 'React.js', value: 'React.js' },
  { label: 'Azure', value: 'Azure' },
  { label: 'Ember.js', value: 'Ember.js' },
  { label: 'Digital Ocean', value: 'Digital Ocean' },
  { label: 'OpenShift', value: 'OpenShift' },
  { label: 'Data modeling', value: 'Data modeling' },
  { label: 'Data design', value: 'Data design' },
  { label: 'ETL', value: 'ETL' },
  { label: 'Spark', value: 'Spark' },
  { label: 'Hadoop', value: 'Hadoop' },
  { label: 'MapReduce', value: 'MapReduce' },
  { label: 'Hive', value: 'Hive' },
  { label: 'Airflow', value: 'Airflow' },
  { label: 'Kafka', value: 'Kafka' },
  { label: 'Sqoop', value: 'Sqoop' },
  { label: 'DWH', value: 'DWH' },
  { label: 'Elastic Stack', value: 'Elastic Stack' },
  { label: 'Kudu', value: 'Kudu' },
  { label: 'Impala', value: 'Impala' },
  { label: 'Azure DataBricks', value: 'Azure DataBricks' },
  { label: 'Azure Data studio', value: 'Azure Data studio' },
  { label: 'Azure Data Factory', value: 'Azure Data Factory' },
  { label: 'Tableau', value: 'Tableau' },
  { label: 'MS Power BI', value: 'MS Power BI' },
  { label: 'Shell', value: 'Shell' },
  { label: 'Linux', value: 'Linux' },
  {
    label: 'Web Scraping (BeautifulSoup, Selenium)',
    value: 'Web Scraping (BeautifulSoup, Selenium)',
  },
  { label: 'EC2', value: 'EC2' },
  { label: 'SageMaker', value: 'SageMaker' },
  { label: 'IBM Cloud Tools', value: 'IBM Cloud Tools' },
  { label: 'Watson', value: 'Watson' },
  { label: 'Cognos', value: 'Cognos' },
  { label: 'Analytics', value: 'Analytics' },
  { label: 'Bluemix', value: 'Bluemix' },
  { label: 'DevOps', value: 'DevOps' },
  { label: 'R', value: 'R' },
  { label: 'PL/SQL', value: 'PL/SQL' },
  { label: 'T/SQL', value: 'T/SQL' },
  { label: 'Pandas', value: 'Pandas' },
  { label: 'BI solution', value: 'BI solution' },
  { label: 'Data wrangling', value: 'Data wrangling' },
  { label: 'Data analysis', value: 'Data analysis' },
  { label: 'QlikView', value: 'QlikView' },
  { label: 'Qlik Sense', value: 'Qlik Sense' },
  { label: 'Ms Excel', value: 'Ms Excel' },
  { label: 'Scikit-learn', value: 'Scikit-learn' },
  { label: 'TensorFlow', value: 'TensorFlow' },
  { label: 'Keras', value: 'Keras' },
  { label: 'PyTorch.', value: 'PyTorch.' },
  { label: 'Watson Labs', value: 'Watson Labs' },
  { label: 'ODA', value: 'ODA' },
  { label: 'MYSQL Server', value: 'MYSQL Server' },
  { label: 'BeautifulSoup', value: 'BeautifulSoup' },
  { label: 'Naive Bayes', value: 'Naive Bayes' },
  { label: 'SVMLinear Regression', value: 'SVMLinear Regression' },
  { label: 'Logistic Regression', value: 'Logistic Regression' },
  { label: 'Decision Trees', value: 'Decision Trees' },
  { label: 'Random Forests.', value: 'Random Forests.' },
  { label: 'Scipy', value: 'Scipy' },
  {
    label: 'Convolutional Neural Networks (CNN)',
    value: 'Convolutional Neural Networks (CNN)',
  },
  {
    label: 'Long Short-Term Memory (LSTM)',
    value: 'Long Short-Term Memory (LSTM)',
  },
  { label: 'RNN', value: 'RNN' },
  {
    label: 'GANs (Generative Adversarial Networks)',
    value: 'GANs (Generative Adversarial Networks)',
  },
  { label: 'YOLO', value: 'YOLO' },
  { label: 'Retina-net', value: 'Retina-net' },
  { label: 'Resnet', value: 'Resnet' },
  { label: 'Densenet', value: 'Densenet' },
  { label: 'Googlenet / Inception', value: 'Googlenet / Inception' },
  { label: 'OpenCV', value: 'OpenCV' },
  { label: 'Scikit-Image', value: 'Scikit-Image' },
  { label: 'Flask', value: 'Flask' },
  { label: 'Falcon', value: 'Falcon' },
  { label: 'Pytorch', value: 'Pytorch' },
  { label: 'GIT', value: 'GIT' },
  { label: 'Matplotlib', value: 'Matplotlib' },
  { label: 'Plotly', value: 'Plotly' },
  { label: 'Seaborn', value: 'Seaborn' },
  { label: 'PyTorch', value: 'PyTorch' },
  { label: 'GPT', value: 'GPT' },
  { label: 'BERT', value: 'BERT' },
  { label: 'Xlnet', value: 'Xlnet' },
  { label: 'NumPy', value: 'NumPy' },
  { label: 'MonkeyLearn', value: 'MonkeyLearn' },
  { label: 'Aylien', value: 'Aylien' },
  { label: 'IBM Watson', value: 'IBM Watson' },
  { label: 'Google Cloud NLP API', value: 'Google Cloud NLP API' },
  { label: 'Amazon Comprehend', value: 'Amazon Comprehend' },
  { label: 'NLTK', value: 'NLTK' },
  { label: 'Stanford Core NLP', value: 'Stanford Core NLP' },
  { label: 'TextBlob', value: 'TextBlob' },
  { label: 'SpaCy', value: 'SpaCy' },
  { label: 'GenSim', value: 'GenSim' },
  { label: 'Apache Spark', value: 'Apache Spark' },
  { label: 'Data Analysis', value: 'Data Analysis' },
  { label: 'Java Script', value: 'Java Script' },
  { label: 'splunk', value: 'splunk' },
  { label: 'Big query', value: 'Big query' },
  { label: 'SSIS', value: 'SSIS' },
  { label: 'Java Programming', value: 'Java Programming' },
  { label: 'AWS Redshift', value: 'AWS Redshift' },
  { label: 'amazon s3', value: 'amazon s3' },
  { label: 'IBM Datastage', value: 'IBM Datastage' },
  { label: 'Informatica', value: 'Informatica' },
  { label: 'SAP BO', value: 'SAP BO' },
  { label: 'PowerBI', value: 'PowerBI' },
  { label: 'C# .NET', value: 'C# .NET' },
  { label: 'TERADATA', value: 'TERADATA' },
  { label: 'ORACLE DB', value: 'ORACLE DB' },
  { label: 'Shell Scripting', value: 'Shell Scripting' },
  { label: 'Unix', value: 'Unix' },
  { label: 'Google Colab', value: 'Google Colab' },
  { label: 'Jupyter Notebook', value: 'Jupyter Notebook' },
  { label: 'JupyterLab', value: 'JupyterLab' },
  { label: 'DVC', value: 'DVC' },
  { label: 'Metabase', value: 'Metabase' },
  { label: 'Redash', value: 'Redash' },
  { label: 'Superset', value: 'Superset' },
  { label: 'Feast', value: 'Feast' },
  { label: 'Katib', value: 'Katib' },
  { label: 'Tune', value: 'Tune' },
  { label: 'Knowledge Repo', value: 'Knowledge Repo' },
  { label: 'Kyso', value: 'Kyso' },
  { label: 'CNVRG', value: 'CNVRG' },
  { label: 'DataRobot', value: 'DataRobot' },
  { label: 'Domino', value: 'Domino' },
  { label: 'H2O', value: 'H2O' },
  { label: 'Hopsworks', value: 'Hopsworks' },
  { label: 'Iguazio', value: 'Iguazio' },
  { label: 'Kubeflow', value: 'Kubeflow' },
  { label: 'Pachyderm', value: 'Pachyderm' },
  { label: 'Sagemaker', value: 'Sagemaker' },
  { label: 'Comet', value: 'Comet' },
  { label: 'Mlflow', value: 'Mlflow' },
  { label: 'Neptune AI', value: 'Neptune AI' },
  { label: 'BentoML', value: 'BentoML' },
  { label: 'Cortex', value: 'Cortex' },
  { label: 'KFServing', value: 'KFServing' },
  { label: 'PredictionIO', value: 'PredictionIO' },
  { label: 'Seldon', value: 'Seldon' },
  { label: 'TensorFlow Serving', value: 'TensorFlow Serving' },
  { label: 'Dask', value: 'Dask' },
  { label: 'Mahout', value: 'Mahout' },
  { label: 'MLlib', value: 'MLlib' },
  { label: 'Modin', value: 'Modin' },
  { label: 'Ray', value: 'Ray' },
  { label: 'Singa', value: 'Singa' },
  { label: 'Kedro', value: 'Kedro' },
  { label: 'Metaflow', value: 'Metaflow' },
  { label: 'CI/CD', value: 'CI/CD' },
  { label: 'Terraform', value: 'Terraform' },
  { label: 'Apache Beam', value: 'Apache Beam' },
  { label: 'TFX', value: 'TFX' },
  { label: 'NOSQL', value: 'NOSQL' },
  { label: 'Data Robot', value: 'Data Robot' },
  { label: 'Dataiku', value: 'Dataiku' },
  { label: 'Others', value: 'Others' },
]

export const EmployerNumOfEmployees = [
  { label: '1-10', value: '1-10' },
  { label: '11-50', value: '11-50' },
  { label: '51-200', value: '51-200' },
  { label: '+200', value: '+200' },
]
